import { expect, test, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";

const baseJob = { id:"00000000-0000-4000-8000-000000000001",status:"queued",progress:0,estimated_cents:40,created_at:"2026-07-17T12:00:00.000Z",request:{prompt:"A blue marble rolls across a white table.",model:"sora-2",seconds:"4",size:"1280x720"},asset:null };
async function baseMocks(page:Page,jobs:any[]=[]){await page.route("**/api/health",r=>r.fulfill({json:{configured:true}}));await page.route("**/api/generations",r=>r.request().method()==="GET"?r.fulfill({json:{jobs}}):r.continue());}

test("shows focused Create and persistent History navigation",async({page})=>{await baseMocks(page);await page.goto("/");await expect(page.getByRole("heading",{name:"Studio"})).toBeVisible();await expect(page.getByLabel("Prompt")).toBeFocused();await expect(page.getByRole("button",{name:/Generate clip/})).toBeDisabled();await expect(page.getByRole("button",{name:/History/})).toBeVisible();await expect(page.getByText("$0.40",{exact:true})).toBeVisible();await expect(page.getByText("Variations",{exact:true})).toHaveCount(0);});

test("offers every create option and accurate confirmation",async({page})=>{await baseMocks(page);await page.goto("/");await page.locator("summary").click();const duration=page.getByLabel("Duration");await expect(duration.locator("option")).toHaveText(["3 seconds","4 seconds","5 seconds","6 seconds","7 seconds","8 seconds","9 seconds","10 seconds","11 seconds","12 seconds"]);await page.getByLabel("Model").selectOption("sora-2-pro");await duration.selectOption("7");await page.getByLabel("Orientation").selectOption("portrait");await page.getByLabel("Resolution").selectOption("1080x1920");await page.getByLabel("Prompt").fill("A paper kite rises above a field.");await expect(page.getByText("$4.90",{exact:true})).toBeVisible();await page.getByRole("button",{name:/Generate clip/}).click();const dialog=page.getByRole("dialog",{name:"Confirm your clip"});await expect(dialog.getByText("Sora 2 Pro",{exact:true})).toBeVisible();await expect(dialog.getByText("7 seconds",{exact:true})).toBeVisible();await expect(dialog.getByText("1080 × 1920",{exact:true})).toBeVisible();await expect(dialog.getByText("None",{exact:true})).toBeVisible();});

test("offers exact 9:16 iPhone camera outputs",async({page})=>{await baseMocks(page);await page.goto("/");await page.locator("summary").click();const orientation=page.getByLabel("Orientation");await expect(orientation.locator("option")).toHaveText(["Landscape","Portrait","iPhone Camera (9:16)"]);await page.getByLabel("Model").selectOption("sora-2-pro");await orientation.selectOption("iphone");await expect(page.getByLabel("Resolution").locator("option")).toHaveText(["720 × 1280","1080 × 1920"]);await expect(page.getByLabel("Resolution")).toHaveValue("720x1280");});

test("submits a newly supported duration unchanged",async({page})=>{await baseMocks(page);let submittedSeconds="";await page.route("**/api/generations",async route=>{if(route.request().method()==="POST"){const body=route.request().postDataBuffer()?.toString()??"";submittedSeconds=/name="seconds"\r\n\r\n([^\r]+)/.exec(body)?.[1]??"";return route.fulfill({status:201,json:{job:{...baseJob,estimated_cents:70,request:{...baseJob.request,seconds:"7"}}}});}return route.fulfill({json:{jobs:[]}});});await page.goto("/");await page.locator("summary").click();await page.getByLabel("Duration").selectOption("7");await page.getByLabel("Prompt").fill(baseJob.request.prompt);await page.getByRole("button",{name:/Generate clip/}).click();await page.getByRole("button",{name:/Confirm & generate/}).click();await expect.poll(()=>submittedSeconds).toBe("7");});

test("submits one multipart request and retains it in History",async({page})=>{await baseMocks(page);let posts=0;await page.route("**/api/generations",async route=>{if(route.request().method()==="POST"){posts++;expect(route.request().postDataBuffer()).toBeTruthy();return route.fulfill({status:201,json:{job:baseJob}});}return route.fulfill({json:{jobs:[]}});});await page.goto("/");await page.getByLabel("Prompt").fill(baseJob.request.prompt);await page.getByRole("button",{name:/Generate clip/}).click();await page.getByRole("button",{name:/Confirm & generate/}).click();await expect(page.getByText("Creating your clip",{exact:true})).toBeVisible();await page.getByRole("button",{name:/History/}).click();await expect(page.locator(".generation-details").getByText(baseJob.request.prompt,{exact:true})).toBeVisible();expect(posts).toBe(1);});

test("accepts mismatched reference dimensions and automatically fits them",async({page})=>{await baseMocks(page);await page.goto("/");const input=page.locator('input[type="file"]');const pixel=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64");await input.setInputFiles({name:"square.png",mimeType:"image/png",buffer:pixel});await expect(page.getByText(/Automatically fitted to output/)).toBeVisible();await page.getByLabel("Prompt").fill("A reference-guided landscape clip.");await page.getByRole("button",{name:/Generate clip/}).click();await expect(page.getByRole("dialog",{name:"Confirm your clip"}).getByText(/fitted to output/)).toBeVisible();});

test("accepts JPEG reference images",async({page})=>{await baseMocks(page);await page.goto("/");await page.locator('input[type="file"]').setInputFiles({name:"reference.jpg",mimeType:"image/jpeg",buffer:readFileSync(".qa-studio.png")});await expect(page.getByText("reference.jpg",{exact:true})).toBeVisible();await page.getByLabel("Prompt").fill("A JPEG-guided landscape clip.");await page.getByRole("button",{name:/Generate clip/}).click();await expect(page.getByRole("dialog",{name:"Confirm your clip"}).getByText(/fitted to output/)).toBeVisible();});

test("shows saved jobs after reload with editor-focused metadata",async({page})=>{const completed={...baseJob,status:"ready",progress:100,asset:{verified:1,byte_count:1572864,mime_type:"video/mp4"},request:{...baseJob.request,prompt:"First line of the prompt.\nSecond line for the editor.",reference:{name:"opening-frame.png",type:"image/png"}}};await baseMocks(page,[completed]);await page.goto("/");await page.getByRole("button",{name:/History/}).click();await expect(page.locator("video.generated-video")).toHaveAttribute("src",`/api/generations/${baseJob.id}/content`);await expect(page.getByRole("link",{name:"Download"})).toBeVisible();const details=page.locator(".generation-details");await expect(details.getByText(completed.request.prompt,{exact:true})).toBeVisible();await expect(details).toContainText("Sora 2");await expect(details).toContainText("4 seconds");await expect(details).toContainText("1280 × 720");await expect(details).toContainText("Landscape");await expect(details).toContainText("1.5 MB");await expect(details).toContainText("MP4");await expect(details).toContainText("$0.40");await expect(details).toContainText("Ready");await expect(details).toContainText("opening-frame.png · PNG");await expect(page.getByRole("button",{name:/View all generations/})).toHaveCount(0);});

test("handles missing output metadata for unfinished and legacy generations",async({page})=>{await baseMocks(page,[baseJob]);await page.goto("/");await page.getByRole("button",{name:/History/}).click();const details=page.locator(".generation-details");await expect(details.getByText("Unavailable",{exact:true})).toHaveCount(2);await expect(details).toContainText("Rendering");await expect(details).toContainText("None");await expect(page.getByRole("link",{name:"Download"})).toHaveCount(0);});

test("keeps the primary action accessible on mobile",async({page})=>{await page.setViewportSize({width:390,height:844});await baseMocks(page);await page.goto("/");await expect(page.getByRole("button",{name:"History"})).toBeVisible();await page.getByLabel("Prompt").fill("A short mobile test clip.");await expect(page.getByRole("button",{name:/Generate clip/})).toBeEnabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();});

test("keeps confirmation actions visible with a very long prompt",async({page})=>{await page.setViewportSize({width:390,height:640});await baseMocks(page);await page.goto("/");await page.getByLabel("Prompt").fill("A detailed cinematic scene with changing light and camera movement. ".repeat(120));await page.getByRole("button",{name:/Generate clip/}).click();const dialog=page.getByRole("dialog",{name:"Confirm your clip"});await expect(dialog).toBeVisible();await expect(page.getByRole("button",{name:/Confirm & generate/})).toBeInViewport();expect(await dialog.evaluate(element=>element.scrollHeight>element.clientHeight)).toBeTruthy();});
