import { expect, test, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { estimateVideoCents, providerVideoSeconds, VIDEO_SECONDS, VIDEO_SIZES, videoRateCents } from "../lib/video-config";
import { buildContinuityPrompt, buildSoraPrompt, validateDialogue } from "../lib/sora-prompt";
import { prepareCharacterReference } from "../lib/video-reference";

const baseJob = { id:"00000000-0000-4000-8000-000000000001",status:"queued",progress:0,estimated_cents:40,created_at:"2026-07-17T12:00:00.000Z",request:{prompt:"A blue marble rolls across a white table.",model:"sora-2",seconds:"4",size:"1280x720"},asset:null };
async function baseMocks(page:Page,jobs:any[]=[]){await page.route("**/api/health",r=>r.fulfill({json:{configured:true}}));await page.route("**/api/characters",r=>r.fulfill({json:{characters:[],limit:5,maxPerGeneration:2}}));await page.route("**/api/generations",r=>r.request().method()==="GET"?r.fulfill({json:{jobs}}):r.continue());}

test("shows focused Create and explains when a prompt is missing",async({page})=>{await baseMocks(page);await page.goto("/");await expect(page.getByRole("heading",{name:"Studio"})).toBeVisible();await expect(page.getByLabel("Prompt")).toBeFocused();const generate=page.getByRole("button",{name:/Generate clip/});await expect(generate).toBeEnabled();await generate.click();await expect(page.locator(".inline-error")).toHaveText("Enter a prompt describing the video you want to generate.");await expect(page.getByRole("button",{name:/History/})).toBeVisible();await expect(page.getByText("$2.80",{exact:true})).toBeVisible();await expect(page.getByText("Variations",{exact:true})).toHaveCount(0);});

test("offers every create option and accurate confirmation",async({page})=>{await baseMocks(page);await page.goto("/");const summaries=page.locator("summary");await expect(summaries).toHaveCount(2);await summaries.nth(1).click();const duration=page.getByLabel("Duration");await expect(duration.locator("option")).toHaveText(VIDEO_SECONDS.map(value=>`${value} seconds`));await page.getByLabel("Model").selectOption("sora-2-pro");await duration.selectOption("7");await page.getByLabel("Orientation").selectOption("portrait");await page.getByLabel("Resolution").selectOption("1080x1920");await page.getByLabel("Prompt").fill("A paper kite rises above a field.");await expect(page.getByText("$5.60",{exact:true})).toBeVisible();await page.getByRole("button",{name:/Generate clip/}).click();const dialog=page.getByRole("dialog",{name:"Confirm your clip"});await expect(dialog.getByText("Sora 2 Pro",{exact:true})).toBeVisible();await expect(dialog.getByText("7 seconds",{exact:true})).toBeVisible();await expect(dialog.getByText("1080 × 1920",{exact:true})).toBeVisible();await expect(dialog.getByText("None",{exact:true})).toHaveCount(3);});

test("defaults new clips to the quality-first Sora configuration",async({page})=>{await baseMocks(page);await page.goto("/");const summaries=page.locator("summary");await expect(summaries).toHaveCount(2);await summaries.nth(1).click();await expect(page.getByLabel("Model")).toHaveValue("sora-2-pro");await expect(page.getByLabel("Resolution")).toHaveValue("1920x1080");await expect(page.getByText("$2.80",{exact:true})).toBeVisible();});

test("presents only the opening-frame image input supported by Sora",async({page})=>{await baseMocks(page);await page.goto("/");await expect(page.locator("label.prompt-label").filter({hasText:"Opening frame reference image"})).toBeVisible();await expect(page.getByLabel("Reference photos",{exact:true})).toHaveCount(0);await expect(page.getByText("Non-opening visual guidance",{exact:false})).toHaveCount(0);});

test("rejects unsupported additional reference photos at the server boundary",async({request})=>{const response=await request.post("/api/generations",{multipart:{prompt:"A product rotates on a table.",model:"sora-2-pro",seconds:"4",size:"1280x720",reference_photos:{name:"extra.png",mimeType:"image/png",buffer:Buffer.from("not-an-image")}}});expect(response.status()).toBe(400);await expect(response.json()).resolves.toEqual({error:"Additional reference photos are not supported by the Sora API. Use one opening-frame reference image."});});

test("rejects model and resolution mismatches before batch submission",async({request})=>{const response=await request.post("/api/generation-batches",{data:{prompt:"A landscape shot.",model:"sora-2",seconds:"4",size:"1920x1080",variations:1,confirmedEstimateCents:280}});expect(response.status()).toBe(400);const body=await response.json();expect(body.error.code).toBe("invalid_generation_request");});

test("shows a five-ID character library and enforces Sora's two-character request limit",async({page})=>{await baseMocks(page);const characters=[1,2,3].map(index=>({id:`local-${index}`,characterId:`char_${index}`,name:`Mascot ${index}`,description:`Character ${index}`,createdAt:"2026-07-20T00:00:00.000Z"}));await page.route("**/api/characters",route=>route.fulfill({json:{characters,limit:5,maxPerGeneration:2}}));await page.goto("/");await page.getByRole("button",{name:/Characters/}).click();await expect(page.getByRole("heading",{name:"Character IDs"})).toBeVisible();await expect(page.locator(".character-library-header").getByText("3/5",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Create",exact:true}).click();const checkboxes=page.locator('.character-id-list input[type="checkbox"]');await expect(checkboxes).toHaveCount(3);await checkboxes.nth(0).check();await checkboxes.nth(1).check();await checkboxes.nth(2).click();await expect(page.getByText("Sora allows 2 total characters across guidance clips and saved Character IDs.",{exact:true})).toBeVisible();await expect(checkboxes.nth(2)).not.toBeChecked();});

test("adds two described MP4 clips as AI-extracted character guidance",async({page})=>{const work=mkdtempSync(path.join(tmpdir(),"sora-reference-"));const firstClip=path.join(work,"mossy.mp4");const secondClip=path.join(work,"pip.mp4");try{const ffmpeg=path.join(process.cwd(),"node_modules","ffmpeg-static","ffmpeg");execFileSync(ffmpeg,["-y","-f","lavfi","-i","color=c=purple:s=320x180:d=6","-pix_fmt","yuv420p",firstClip]);execFileSync(ffmpeg,["-y","-f","lavfi","-i","color=c=gold:s=320x180:d=4","-pix_fmt","yuv420p",secondClip]);await baseMocks(page);let submittedBody="";await page.route("**/api/generations",async route=>{if(route.request().method()==="POST"){submittedBody=route.request().postDataBuffer()?.toString("latin1")??"";return route.fulfill({status:201,json:{job:baseJob}});}return route.fulfill({json:{jobs:[]}});});await page.goto("/");await page.getByLabel("Reference video").setInputFiles(firstClip);await expect(page.getByText("mossy.mp4",{exact:true})).toBeVisible();await expect(page.getByText(/6\.0 seconds · AI selects a silent 2–4s segment/)).toBeVisible();await page.getByLabel("Guidance character 1 name").fill("Mossy");await page.getByLabel("Guidance character 1 description").fill("A round purple felt mascot with a silver leaf pin.");await page.getByRole("button",{name:"Add another character guidance clip"}).click();await page.getByLabel("Reference video 2").setInputFiles(secondClip);await page.getByLabel("Guidance character 2 name").fill("Pip");await page.getByLabel("Guidance character 2 description").fill("A small gold robot with a square blue chest light.");await page.getByLabel("Prompt").fill("Mossy turns toward Pip.");await page.getByRole("button",{name:/Generate clip/}).click();const dialog=page.getByRole("dialog");await expect(dialog.getByText(/Mossy · A round purple felt mascot with a silver leaf pin\./)).toBeVisible();await expect(dialog.getByText(/Pip · A small gold robot with a square blue chest light\./)).toBeVisible();await page.getByRole("button",{name:/Confirm & generate/}).click();await expect.poll(()=>(submittedBody.match(/name="video_references"/g)??[]).length).toBe(2);expect(submittedBody).toContain("video_reference_metadata");expect(submittedBody).toContain("A round purple felt mascot with a silver leaf pin.");expect(submittedBody).toContain("A small gold robot with a square blue chest light.");}finally{rmSync(work,{recursive:true,force:true});}});

test("rejects more than two AI-extracted guidance clips at the server boundary",async({request})=>{const boundary="----codex-guidance-limit";const field=(name:string,value:string)=>`--${boundary}\r\nContent-Disposition: form-data; name="${name}"\r\n\r\n${value}\r\n`;const file=(name:string)=>`--${boundary}\r\nContent-Disposition: form-data; name="video_references"; filename="${name}"\r\nContent-Type: video/mp4\r\n\r\ntest\r\n`;const body=field("prompt","Three characters enter.")+field("model","sora-2-pro")+field("seconds","4")+field("size","1280x720")+field("video_reference_metadata",JSON.stringify([{characterName:"One",description:"First character."},{characterName:"Two",description:"Second character."},{characterName:"Three",description:"Third character."}]))+file("one.mp4")+file("two.mp4")+file("three.mp4")+`--${boundary}--\r\n`;const response=await request.post("/api/generations",{headers:{"content-type":`multipart/form-data; boundary=${boundary}`},data:Buffer.from(body)});expect(response.status()).toBe(400);await expect(response.json()).resolves.toEqual({error:"Sora allows at most 2 AI-extracted character guidance clips."});});

test("creates the FFmpeg output folder for a short vertical guidance clip",async()=>{const work=mkdtempSync(path.join(tmpdir(),"sora-short-reference-"));const source=path.join(work,"short-vertical.mp4");const outputDir=path.join(work,"missing","character-guidance-1");const originalFetch=globalThis.fetch;const originalKey=process.env.OPENAI_API_KEY;try{execFileSync(path.join(process.cwd(),"node_modules","ffmpeg-static","ffmpeg"),["-y","-f","lavfi","-i","color=c=purple:s=856x1072:d=3.04:r=24","-pix_fmt","yuv420p",source],{stdio:"ignore"});process.env.OPENAI_API_KEY="test-key";globalThis.fetch=async()=>new Response(JSON.stringify({id:"char_test"}),{status:200,headers:{"content-type":"application/json"}});const result=await prepareCharacterReference(source,"Mossy turns toward the camera.",outputDir,"Mossy");expect(result.id).toBe("char_test");expect(result.selectedDuration).toBeCloseTo(3.04,1);expect(existsSync(path.join(outputDir,"reference-character.mp4"))).toBeTruthy();}finally{globalThis.fetch=originalFetch;if(originalKey===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=originalKey;rmSync(work,{recursive:true,force:true});}});

test("maps every requested duration to a supported Sora render length",()=>{expect(VIDEO_SECONDS.map(value=>providerVideoSeconds(value))).toEqual(["4","4","8","8","8","8","12","12","12","12","16","16","16","16","20","20","20","20"]);});

test("builds one visible final prompt with dialogue ownership, described extracted characters, and guardrails",()=>{const result=buildSoraPrompt({prompt:"Mossy faces Pip.",dialogue:'Mossy: \"Hello.\"\nPip: \"Hi.\"',audioDirection:"Mossy is low and calm; Pip is bright and quick.",extractedCharacters:[{name:"Mossy",description:"round purple felt mascot with a silver leaf pin"}],characters:[{name:"Pip",description:"small brass robot"}]});expect(result).toContain("Mossy: round purple felt mascot with a silver leaf pin");expect(result).toContain("<dialogue>");expect(result).toContain('- Mossy: \"Hello.\"');expect(result).toContain("Only the labeled speaker says each line.");expect(result).toContain("Do not invent extra characters");expect(validateDialogue('\"Hello\"')).toMatch(/Speaker/);});

test("offers exact 9:16 iPhone camera outputs",async({page})=>{await baseMocks(page);await page.goto("/");await page.locator("summary").filter({hasText:"Output options"}).click();const orientation=page.getByLabel("Orientation");await expect(orientation.locator("option")).toHaveText(["Landscape","Portrait","iPhone Camera (9:16)"]);await page.getByLabel("Model").selectOption("sora-2-pro");await orientation.selectOption("iphone");await expect(page.getByLabel("Resolution").locator("option")).toHaveText(["720 × 1280","1080 × 1920"]);await expect(page.getByLabel("Resolution")).toHaveValue("1080x1920");});

test("preserves the matching quality tier when orientation changes",async({page})=>{await baseMocks(page);await page.goto("/");await page.locator("summary").filter({hasText:"Output options"}).click();await page.getByLabel("Resolution").selectOption("1280x720");await page.getByLabel("Duration").selectOption("9");await expect(page.getByText("$3.60",{exact:true})).toBeVisible();await expect(page.getByText(/Billed as 12s at \$0\.30\/second/)).toBeVisible();await page.getByLabel("Orientation").selectOption("iphone");await expect(page.getByLabel("Resolution")).toHaveValue("720x1280");await expect(page.getByText("$3.60",{exact:true})).toBeVisible();await page.getByLabel("Resolution").selectOption("1080x1920");await expect(page.getByText("$8.40",{exact:true})).toBeVisible();await expect(page.getByText(/Billed as 12s at \$0\.70\/second/)).toBeVisible();});

test("calculates every supported model, duration, and resolution from official per-second tiers",()=>{for(const model of ["sora-2","sora-2-pro"] as const){for(const size of VIDEO_SIZES[model]){const expectedRate=model==="sora-2"?10:/1920|1080/.test(size)?70:/1792|1024/.test(size)?50:30;expect(videoRateCents(model,size)).toBe(expectedRate);for(const seconds of VIDEO_SECONDS)expect(estimateVideoCents(model,size,seconds)).toBe(expectedRate*Number(providerVideoSeconds(seconds)));}}});

test("submits a newly supported duration unchanged",async({page})=>{await baseMocks(page);let submittedSeconds="";await page.route("**/api/generations",async route=>{if(route.request().method()==="POST"){const body=route.request().postDataBuffer()?.toString()??"";submittedSeconds=/name="seconds"\r\n\r\n([^\r]+)/.exec(body)?.[1]??"";return route.fulfill({status:201,json:{job:{...baseJob,estimated_cents:70,request:{...baseJob.request,seconds:"7"}}}});}return route.fulfill({json:{jobs:[]}});});await page.goto("/");await page.locator("summary").filter({hasText:"Output options"}).click();await page.getByLabel("Duration").selectOption("7");await page.getByLabel("Prompt").fill(baseJob.request.prompt);await page.getByRole("button",{name:/Generate clip/}).click();await page.getByRole("button",{name:/Confirm & generate/}).click();await expect.poll(()=>submittedSeconds).toBe("7");});

test("submits one multipart request and retains it in History",async({page})=>{await baseMocks(page);let posts=0;await page.route("**/api/generations",async route=>{if(route.request().method()==="POST"){posts++;expect(route.request().postDataBuffer()).toBeTruthy();return route.fulfill({status:201,json:{job:baseJob}});}return route.fulfill({json:{jobs:[]}});});await page.goto("/");await page.getByLabel("Prompt").fill(baseJob.request.prompt);await page.getByRole("button",{name:/Generate clip/}).click();await page.getByRole("button",{name:/Confirm & generate/}).click();await expect(page.getByText("Creating your clip",{exact:true})).toBeVisible();await page.getByRole("button",{name:/History/}).click();await expect(page.locator(".generation-details").getByText(baseJob.request.prompt,{exact:true})).toBeVisible();expect(posts).toBe(1);});

test("accepts mismatched reference dimensions and automatically fits them",async({page})=>{await baseMocks(page);await page.goto("/");const input=page.getByLabel("Opening frame reference image");const pixel=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64");await input.setInputFiles({name:"square.png",mimeType:"image/png",buffer:pixel});await expect(page.getByText(/Used as frame 1 and fitted to output/)).toBeVisible();await page.getByLabel("Prompt").fill("A reference-guided landscape clip.");await page.getByRole("button",{name:/Generate clip/}).click();await expect(page.getByRole("dialog",{name:"Confirm your clip"}).getByText(/fitted to output/)).toBeVisible();});

test("accepts JPEG reference images",async({page})=>{await baseMocks(page);await page.goto("/");await page.getByLabel("Opening frame reference image").setInputFiles({name:"reference.jpg",mimeType:"image/jpeg",buffer:readFileSync(".qa-studio.png")});await expect(page.getByText("reference.jpg",{exact:true})).toBeVisible();await page.getByLabel("Prompt").fill("A JPEG-guided landscape clip.");await page.getByRole("button",{name:/Generate clip/}).click();await expect(page.getByRole("dialog",{name:"Confirm your clip"}).getByText(/fitted to output/)).toBeVisible();});

test("shows saved jobs after reload with editor-focused metadata",async({page})=>{const completed={...baseJob,status:"ready",progress:100,asset:{verified:1,byte_count:1572864,mime_type:"video/mp4"},request:{...baseJob.request,prompt:"First line of the prompt.\nSecond line for the editor.",reference:{name:"opening-frame.png",type:"image/png"}}};await baseMocks(page,[completed]);await page.goto("/");await page.getByRole("button",{name:/History/}).click();await expect(page.locator("video.generated-video")).toHaveAttribute("src",`/api/generations/${baseJob.id}/content`);await expect(page.getByRole("link",{name:"Download"})).toBeVisible();const details=page.locator(".generation-details");await expect(details.getByText(completed.request.prompt,{exact:true})).toBeVisible();await expect(details).toContainText("Sora 2");await expect(details).toContainText("4 seconds");await expect(details).toContainText("1280 × 720");await expect(details).toContainText("Landscape");await expect(details).toContainText("1.5 MB");await expect(details).toContainText("MP4");await expect(details).toContainText("$0.40");await expect(details).toContainText("Ready");await expect(details).toContainText("opening-frame.png · PNG");await expect(page.getByRole("button",{name:/View all generations/})).toHaveCount(0);});

test("handles missing output metadata for unfinished and legacy generations",async({page})=>{await baseMocks(page,[baseJob]);await page.goto("/");await page.getByRole("button",{name:/History/}).click();const details=page.locator(".generation-details");await expect(details.getByText("Unavailable",{exact:true})).toHaveCount(2);await expect(details).toContainText("Rendering");await expect(details).toContainText("None");await expect(page.getByRole("link",{name:"Download"})).toHaveCount(0);});

test("does not present an uncertain submission as actively rendering",async({page})=>{await baseMocks(page,[{...baseJob,status:"submission_unknown",error_message:"Submission connection timed out."}]);await page.goto("/");await expect(page.getByText("Submission uncertain",{exact:true})).toBeVisible();await expect(page.getByText("Submission connection timed out.",{exact:true})).toBeVisible();await page.getByRole("button",{name:/History/}).click();await expect(page.getByText("Submission uncertain",{exact:true}).first()).toBeVisible();});

test("keeps the primary action accessible on mobile",async({page})=>{await page.setViewportSize({width:390,height:844});await baseMocks(page);await page.goto("/");await expect(page.getByRole("button",{name:"History"})).toBeVisible();await page.getByLabel("Prompt").fill("A short mobile test clip.");await expect(page.getByRole("button",{name:/Generate clip/})).toBeEnabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();});

test("keeps confirmation actions visible with a very long prompt",async({page})=>{await page.setViewportSize({width:390,height:640});await baseMocks(page);await page.goto("/");await page.getByLabel("Prompt").fill("A detailed cinematic scene with changing light and camera movement. ".repeat(120));await page.getByRole("button",{name:/Generate clip/}).click();const dialog=page.getByRole("dialog",{name:"Confirm your clip"});await expect(dialog).toBeVisible();await expect(page.getByRole("button",{name:/Confirm & generate/})).toBeInViewport();expect(await dialog.evaluate(element=>element.scrollHeight>element.clientHeight)).toBeTruthy();});

test("builds continuity prompts that preserve the source and constrain edits",()=>{const extension=buildContinuityPrompt({mode:"extend",prompt:"Mossy hands Pip the key.",dialogue:'Mossy: "It is yours."',audioDirection:"Keep Mossy's low, calm voice."});expect(extension).toContain("Continue the supplied Sora video directly from its final moment.");expect(extension).toContain("Do not restart, recap");expect(extension).toContain("Only the labeled speaker says each line.");const edit=buildContinuityPrompt({mode:"edit",prompt:"Change only the umbrella from red to green."});expect(edit).toContain("Make one targeted edit");expect(edit).toContain("Preserve its duration, timing, character identities");expect(edit).toContain("Change only: Change only the umbrella");});

test("exposes every supported continuity component and the exact transformed prompt",async({page})=>{const source={...baseJob,status:"ready",progress:100,provider_video_id:"video_source_123",asset:{verified:1,byte_count:1572864,mime_type:"video/mp4"},request:{...baseJob.request,prompt:"Mossy and Pip wait beside a brass door.",model:"sora-2-pro",size:"1920x1080",characters:[{id:"char_mossy",name:"Mossy",description:"A round purple felt mascot."}]}};await baseMocks(page,[source]);let body:any=null;await page.route("**/api/continuity",async route=>{body=route.request().postDataJSON();const job={...source,id:"00000000-0000-4000-8000-000000000099",status:"queued",asset:null,request:{prompt:body.prompt,model:"sora-2-pro",seconds:body.seconds,totalSeconds:11,size:"1920x1080",continuity:{mode:body.mode,sourceJobId:source.id,chainRootJobId:source.id,extensionDepth:1,sourceTotalSeconds:4,appendedSeconds:body.seconds}}};await route.fulfill({status:201,json:{job}});});await page.goto("/");await page.getByRole("button",{name:"Continuity",exact:true}).click();await expect(page.getByRole("heading",{name:"Continuity Chain"})).toBeVisible();await expect(page.getByLabel("Source clip")).toHaveValue(source.id);await expect(page.getByText("What Sora inherits",{exact:true})).toBeVisible();await expect(page.getByText("Not accepted on this endpoint",{exact:true})).toBeVisible();await expect(page.getByText(/Opening-frame images, Character IDs, and AI-extracted character guidance/)).toBeVisible();await page.getByLabel("Continuation length").selectOption("7");await page.getByLabel("Next scene").fill("Mossy hands Pip the key without a cut.");await page.getByRole("button",{name:"Review continuation"}).click();const dialog=page.getByRole("dialog",{name:"Confirm continuation"});await expect(dialog.getByText(/Continue the supplied Sora video directly from its final moment/)).toBeVisible();await expect(dialog.getByText("Not sent; source video only",{exact:true})).toBeVisible();await dialog.getByRole("button",{name:"Confirm & send"}).click();await expect.poll(()=>body).not.toBeNull();expect(body).toMatchObject({sourceJobId:source.id,mode:"extend",seconds:"7",prompt:"Mossy hands Pip the key without a cut."});expect(body).not.toHaveProperty("characters");expect(body).not.toHaveProperty("input_reference");});

test("opens targeted edit directly from a ready History clip",async({page})=>{const source={...baseJob,status:"ready",progress:100,provider_video_id:"video_source_edit",asset:{verified:1,byte_count:1572864,mime_type:"video/mp4"}};await baseMocks(page,[source]);await page.goto("/");await page.getByRole("button",{name:/History/}).click();await page.getByRole("button",{name:"Targeted edit"}).click();await expect(page.getByRole("heading",{name:"Continuity Chain"})).toBeVisible();await expect(page.getByRole("radio",{name:/Targeted edit/})).toBeChecked();await expect(page.getByLabel("Continuation length")).toHaveCount(0);await page.getByLabel("Change only").fill("Change only the marble from blue to green.");await page.getByRole("button",{name:"Review edit"}).click();await expect(page.getByRole("dialog",{name:"Confirm targeted edit"}).getByText(/Make one targeted edit/)).toBeVisible();});
