"use client";

import { DragEvent, FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { BookUser, Check, ChevronDown, Download, Film, History, ImagePlus, LoaderCircle, Plus, Trash2, WandSparkles, X } from "lucide-react";
import { estimateVideoCents, VIDEO_SECONDS, VIDEO_SIZES, type VideoModel, type VideoSeconds } from "../lib/video-config";

type View = "create" | "characters" | "history";
type Orientation = "landscape" | "portrait" | "iphone";
type Character = { id:string; characterId:string; name:string; description:string; createdAt:string };
type Job = { id:string; status:string; progress:number; estimated_cents:number; error_message?:string; created_at:string; request:{prompt:string;model:VideoModel;seconds:VideoSeconds;size:string;reference?:{name:string;type:string;path?:string;storedFile?:string};videoReference?:{name:string;type:string;storedFile?:string;selectedStart?:number;selectedDuration?:number};characters?:Array<{id:string;name:string;description:string}>}; asset?:{verified:number;byte_count?:number|null;mime_type?:string|null} };

const labels: Record<VideoModel,string> = { "sora-2":"Sora 2", "sora-2-pro":"Sora 2 Pro" };
const fmtSize = (size:string) => size.replace("x", " × ");
const ready = (job:Job) => job.status === "ready" && Boolean(job.asset?.verified);
const active = (job:Job) => ["draft","submitting","submission_unknown","queued","in_progress","completed","archiving","archive_failed"].includes(job.status);
const statusLabel = (job:Job) => ready(job) ? "Ready" : job.status === "failed" || job.status === "moderation_blocked" ? "Failed" : active(job) ? "Rendering" : job.status.replaceAll("_", " ");
const outputOrientation = (size:string) => { const [width,height]=size.split("x").map(Number); return width>height?"Landscape":width<height?"Portrait":"Square"; };
const fileSize = (bytes?:number|null) => bytes ? `${(bytes/1024/1024).toFixed(1)} MB` : "Unavailable";
const fileFormat = (mime?:string|null) => mime ? mime.split("/").at(-1)?.toUpperCase() ?? mime : "Unavailable";
const referenceFormat = (mime:string) => mime.split("/").at(-1)?.toUpperCase() ?? mime;
const isIPhoneFrame = (size:string) => { const [width,height]=size.split("x").map(Number); return width*16===height*9; };

export default function Home() {
  const [view,setView] = useState<View>("create"); const [jobs,setJobs] = useState<Job[]>([]); const [selectedId,setSelectedId] = useState<string|null>(null);
  const [prompt,setPrompt] = useState(""); const [model,setModel] = useState<VideoModel>("sora-2-pro"); const [seconds,setSeconds] = useState<VideoSeconds>("4"); const [orientation,setOrientation] = useState<Orientation>("landscape"); const [size,setSize] = useState("1920x1080");
  const [reference,setReference] = useState<File|null>(null); const [referenceUrl,setReferenceUrl] = useState(""); const [referenceError,setReferenceError] = useState(""); const [referenceAdjusted,setReferenceAdjusted] = useState(false);
  const [videoReference,setVideoReference] = useState<File|null>(null); const [videoReferenceUrl,setVideoReferenceUrl] = useState(""); const [videoReferenceDuration,setVideoReferenceDuration] = useState<number|null>(null); const [videoReferenceError,setVideoReferenceError] = useState("");
  const [characters,setCharacters] = useState<Character[]>([]); const [selectedCharacterIds,setSelectedCharacterIds] = useState<string[]>([]);
  const [confirm,setConfirm] = useState(false); const [submitting,setSubmitting] = useState(false); const [error,setError] = useState(""); const [connected,setConnected] = useState(false);
  const selected = useMemo(()=>jobs.find(job=>job.id===selectedId) ?? jobs[0] ?? null,[jobs,selectedId]);
  const sizes = useMemo(()=>(VIDEO_SIZES[model] as readonly string[]).filter(value=>orientation === "landscape" ? Number(value.split("x")[0]) > Number(value.split("x")[1]) : orientation === "iphone" ? isIPhoneFrame(value) : Number(value.split("x")[0]) < Number(value.split("x")[1])),[model,orientation]);
  const cents = estimateVideoCents(model,size,seconds);

  const loadJobs = useCallback(async()=>{ const response=await fetch("/api/generations",{cache:"no-store"}); if(response.ok){const data=await response.json();setJobs(data.jobs);setSelectedId(current=>current ?? data.jobs[0]?.id ?? null);}},[]);
  const loadCharacters = useCallback(async()=>{const response=await fetch("/api/characters",{cache:"no-store"});if(response.ok){const data=await response.json();setCharacters(data.characters);setSelectedCharacterIds(current=>current.filter(id=>data.characters.some((character:Character)=>character.characterId===id)));}},[]);
  useEffect(()=>{loadJobs();loadCharacters();fetch("/api/health").then(r=>r.json()).then(d=>setConnected(Boolean(d.configured))).catch(()=>{});},[loadJobs,loadCharacters]);
  useEffect(()=>{setSize(current=>sizes.includes(current)?current:sizes.at(-1)??"1280x720");},[model,orientation,sizes]);
  useEffect(()=>()=>{if(referenceUrl)URL.revokeObjectURL(referenceUrl);},[referenceUrl]);
  useEffect(()=>()=>{if(videoReferenceUrl)URL.revokeObjectURL(videoReferenceUrl);},[videoReferenceUrl]);
  useEffect(()=>{const ids=jobs.filter(active).map(job=>job.id);if(!ids.length)return;const timer=window.setInterval(async()=>{const updates=await Promise.all(ids.map(id=>fetch(`/api/generations/${id}`,{cache:"no-store"}).then(r=>r.json()).then(d=>d.job).catch(()=>null)));setJobs(current=>current.map(job=>updates.find(item=>item?.id===job.id)??job));},3000);return()=>clearInterval(timer);},[jobs]);

  function chooseReference(file:File|null){setReferenceError("");setReferenceAdjusted(false);if(!file){setReference(null);setReferenceUrl("");return;}if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setReferenceError("Choose a JPEG, PNG, or WebP image.");return;}if(file.size>20*1024*1024){setReferenceError("Reference images must be 20 MB or smaller.");return;}setReference(file);setReferenceUrl(URL.createObjectURL(file));}
  function drop(event:DragEvent){event.preventDefault();chooseReference(event.dataTransfer.files[0]??null);}
  async function chooseVideoReference(file:File|null){setVideoReferenceError("");if(videoReferenceUrl)URL.revokeObjectURL(videoReferenceUrl);if(!file){setVideoReference(null);setVideoReferenceUrl("");setVideoReferenceDuration(null);return;}if(selectedCharacterIds.length>=2){setVideoReferenceError("Remove one selected character ID before adding a reference video. Sora allows 2 characters per generation.");return;}if(file.type!=="video/mp4"){setVideoReferenceError("Choose an MP4 video clip.");return;}if(file.size>100*1024*1024){setVideoReferenceError("Reference videos must be 100 MB or smaller.");return;}const url=URL.createObjectURL(file);try{const duration=await new Promise<number>((resolve,reject)=>{const video=document.createElement("video");video.preload="metadata";video.onloadedmetadata=()=>resolve(video.duration);video.onerror=()=>reject(new Error("The MP4 clip could not be read."));video.src=url;});if(!Number.isFinite(duration)||duration<2||duration>8.05)throw new Error("Reference videos must be between 2 and 8 seconds long.");setVideoReference(file);setVideoReferenceUrl(url);setVideoReferenceDuration(duration);}catch(cause){URL.revokeObjectURL(url);setVideoReferenceError(cause instanceof Error?cause.message:"The MP4 clip could not be read.");}}
  function toggleCharacter(characterId:string){setVideoReferenceError("");setSelectedCharacterIds(current=>{if(current.includes(characterId))return current.filter(id=>id!==characterId);const limit=videoReference?1:2;if(current.length>=limit){setVideoReferenceError(`Sora allows ${videoReference?"1 saved character ID alongside a reference video":"2 character IDs"} per generation.`);return current;}return [...current,characterId];});}
  async function prepareReference(){if(!reference)return null;const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const value=new Image();value.onload=()=>resolve(value);value.onerror=()=>reject(new Error("The reference image could not be read."));value.src=referenceUrl;});const [targetWidth,targetHeight]=size.split("x").map(Number);setReferenceAdjusted(image.naturalWidth!==targetWidth||image.naturalHeight!==targetHeight);if(image.naturalWidth===targetWidth&&image.naturalHeight===targetHeight)return reference;const canvas=document.createElement("canvas");canvas.width=targetWidth;canvas.height=targetHeight;const context=canvas.getContext("2d");if(!context)throw new Error("The reference image could not be prepared.");context.imageSmoothingEnabled=true;context.imageSmoothingQuality="high";const scale=Math.max(targetWidth/image.naturalWidth,targetHeight/image.naturalHeight);const width=image.naturalWidth*scale;const height=image.naturalHeight*scale;context.drawImage(image,(targetWidth-width)/2,(targetHeight-height)/2,width,height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,reference.type,1));if(!blob)throw new Error("The reference image could not be prepared.");return new File([blob],reference.name,{type:reference.type,lastModified:reference.lastModified});}
  async function review(event:FormEvent){event.preventDefault();setError("");if(!prompt.trim()){setError("Enter a prompt describing the video you want to generate.");return;}try{await prepareReference();setConfirm(true);}catch(cause){setReferenceError(cause instanceof Error?cause.message:"The reference image could not be prepared.");}}
  async function generate(){if(submitting)return;setSubmitting(true);setError("");try{const preparedReference=await prepareReference();const form=new FormData();form.set("prompt",prompt.trim());form.set("model",model);form.set("seconds",seconds);form.set("size",size);form.set("character_ids",JSON.stringify(selectedCharacterIds));if(preparedReference)form.set("input_reference",preparedReference);if(videoReference)form.set("video_reference",videoReference);const response=await fetch("/api/generations",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"Video request failed.");setJobs(current=>[data.job,...current]);setSelectedId(data.job.id);setConfirm(false);setView("create");}catch(cause){setError(cause instanceof Error?cause.message:"Video request failed.");setConfirm(false);}finally{setSubmitting(false);}}
  function reuse(job:Job){setPrompt(job.request.prompt);setModel(job.request.model);setSeconds(job.request.seconds);setOrientation(Number(job.request.size.split("x")[0])>Number(job.request.size.split("x")[1])?"landscape":"portrait");setSize(job.request.size);chooseReference(null);void chooseVideoReference(null);setSelectedCharacterIds(job.request.characters?.map(character=>character.id)??[]);setView("create");}

  return <main className="app-shell">
    <aside className="side-nav"><div className="brand-lockup"><span className="brand-mark"><WandSparkles size={18}/></span><div><span className="eyebrow">VIDEO GENERATOR</span><h1>Studio</h1></div></div><nav aria-label="Main navigation"><button className={view==="create"?"active":""} onClick={()=>setView("create")}><Plus size={17}/>Create</button><button className={view==="characters"?"active":""} onClick={()=>setView("characters")}><BookUser size={17}/>Characters <span>{characters.length}/5</span></button><button className={view==="history"?"active":""} onClick={()=>setView("history")}><History size={17}/>History <span>{jobs.length}</span></button></nav><div className="nav-status"><span className={`status-dot ${connected?"green":"amber"}`}/>{connected?"OpenAI connected":"Setup required"}</div></aside>
    <section className="app-content"><header className="mobile-header"><strong>Studio</strong><button onClick={()=>setView(view==="create"?"history":"create")}>{view==="create"?<History size={18}/>:<Plus size={18}/>} {view==="create"?"History":"Create"}</button></header>
    {view==="create"?<div className="studio-grid"><section className="composer-card"><div className="section-intro"><span className="section-number">01</span><div><h2>Create a video</h2><p>Describe one clip and optionally guide its opening frame.</p></div></div><form onSubmit={review}>
      <label className="prompt-label" htmlFor="prompt">Prompt</label><div className="prompt-wrap"><textarea id="prompt" value={prompt} maxLength={32000} onChange={e=>setPrompt(e.target.value)} placeholder="A quiet desert road at dusk, slow tracking shot, warm cinematic light…" rows={7} autoFocus/><span className="character-count">{prompt.length}</span></div>
      <label className="prompt-label">Reference image <span>Optional</span></label>{reference?<div className="reference-preview"><img src={referenceUrl} alt="Reference preview"/><div><strong>{reference.name}</strong><span>{(reference.size/1024/1024).toFixed(1)} MB · Automatically fitted to output</span><label className="text-button">Replace<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseReference(e.target.files?.[0]??null)}/></label></div><button type="button" aria-label="Remove reference image" onClick={()=>chooseReference(null)}><Trash2 size={16}/></button></div>:<label className="reference-drop" onDragOver={e=>e.preventDefault()} onDrop={drop}><ImagePlus size={21}/><strong>Add an opening frame</strong><span>Any aspect ratio · automatically center-cropped to fit</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseReference(e.target.files?.[0]??null)}/></label>}{referenceError&&<div className="inline-error" role="alert">{referenceError}</div>}
      <label className="prompt-label">Reference video <span>Optional</span></label>{videoReference?<div className="reference-preview video-reference-preview"><video src={videoReferenceUrl} muted playsInline/><div><strong>{videoReference.name}</strong><span>{videoReferenceDuration?.toFixed(1)} seconds · Best 4 seconds selected from prompt</span><label className="text-button">Replace<input hidden type="file" accept="video/mp4" onChange={e=>void chooseVideoReference(e.target.files?.[0]??null)}/></label></div><button type="button" aria-label="Remove reference video" onClick={()=>void chooseVideoReference(null)}><Trash2 size={16}/></button></div>:<label className="reference-drop video-reference-drop"><Film size={21}/><strong>Add a character reference clip</strong><span>MP4 · 2–8 seconds · automatically reduced to the best 4 seconds</span><input aria-label="Reference video" type="file" accept="video/mp4" onChange={e=>void chooseVideoReference(e.target.files?.[0]??null)}/></label>}{videoReferenceError&&<div className="inline-error" role="alert">{videoReferenceError}</div>}<p className="reference-note">For non-human subjects such as animals, mascots, or objects. Human likeness requires eligible OpenAI access.</p>
      <div className="character-picker"><div className="character-picker-heading"><strong>Character IDs</strong><span>{selectedCharacterIds.length}/{videoReference?1:2} selected · {characters.length}/5 saved</span></div>{characters.length?<div className="character-id-list">{characters.map(character=><label key={character.id} className={selectedCharacterIds.includes(character.characterId)?"selected":""}><input type="checkbox" checked={selectedCharacterIds.includes(character.characterId)} onChange={()=>toggleCharacter(character.characterId)}/><span><strong>{character.name}</strong><small>{character.characterId}</small></span></label>)}</div>:<button type="button" className="empty-character-link" onClick={()=>setView("characters")}><BookUser size={15}/>Create your first character ID</button>}<p>Sora supports up to two characters in one generated video.</p></div>
      <details className="output-options"><summary><span><span className="section-number">02</span>Output options</span><ChevronDown size={16}/></summary><div className="options-grid"><label>Model<select aria-label="Model" value={model} onChange={e=>setModel(e.target.value as VideoModel)}><option value="sora-2">Sora 2</option><option value="sora-2-pro">Sora 2 Pro</option></select></label><label>Duration<select aria-label="Duration" value={seconds} onChange={e=>setSeconds(e.target.value as VideoSeconds)}>{VIDEO_SECONDS.map(value=><option key={value} value={value}>{value} seconds</option>)}</select></label><label>Orientation<select aria-label="Orientation" value={orientation} onChange={e=>setOrientation(e.target.value as Orientation)}><option value="landscape">Landscape</option><option value="portrait">Portrait</option><option value="iphone">iPhone Camera (9:16)</option></select></label><label>Resolution<select aria-label="Resolution" value={size} onChange={e=>setSize(e.target.value)}>{sizes.map(value=><option key={value} value={value}>{fmtSize(value)}</option>)}</select></label></div></details>
      <div className="generation-summary"><div><span>Estimated total</span><strong>${(cents/100).toFixed(2)}</strong></div><p>One {seconds}-second clip · {labels[model]} · {fmtSize(size)}</p></div>{error&&<div className="inline-error" role="alert">{error}</div>}<button className="generate-button" disabled={submitting}>{submitting?<LoaderCircle className="spin" size={17}/>:<WandSparkles size={17}/>}Generate clip</button>
    </form></section><Result job={selected}/></div>:view==="characters"?<CharactersView characters={characters} onChanged={loadCharacters}/>:<HistoryView jobs={jobs} selected={selected} onSelect={setSelectedId} onReuse={reuse}/>}</section>
    {confirm&&<div className="modal-backdrop" onClick={()=>!submitting&&setConfirm(false)}><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title" onClick={e=>e.stopPropagation()}><div className="modal-topline"><span className="modal-kicker">READY TO GENERATE</span><button className="icon-button" aria-label="Close confirmation" onClick={()=>setConfirm(false)}><X size={17}/></button></div><h2 id="confirm-title">Confirm your clip</h2><p className="modal-copy">This creates one video and saves it to this project.</p><div className="request-summary"><span>Prompt</span><strong>{prompt.trim()}</strong><dl><div><dt>Model</dt><dd>{labels[model]}</dd></div><div><dt>Duration</dt><dd>{seconds} seconds</dd></div><div><dt>Output</dt><dd>{fmtSize(size)}</dd></div><div><dt>Reference image</dt><dd>{reference?`${reference.name}${referenceAdjusted?" · fitted to output":""}`:"None"}</dd></div><div><dt>Reference video</dt><dd>{videoReference?`${videoReference.name} · prompt-selected 4s segment`:"None"}</dd></div><div><dt>Character IDs</dt><dd>{selectedCharacterIds.length?characters.filter(character=>selectedCharacterIds.includes(character.characterId)).map(character=>character.name).join(", "):"None"}</dd></div><div><dt>Estimated total</dt><dd>${(cents/100).toFixed(2)}</dd></div></dl></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setConfirm(false)}>Back</button><button className="generate-button compact" onClick={generate} disabled={submitting}>{submitting?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>}Confirm & generate</button></div></div></div>}
  </main>;
}

function CharactersView({characters,onChanged}:{characters:Character[];onChanged:()=>Promise<void>}){
  const [name,setName]=useState("");const [description,setDescription]=useState("");const [image,setImage]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function create(event:FormEvent){event.preventDefault();setMessage("");if(!image){setMessage("Choose a reference image.");return;}setBusy(true);try{const form=new FormData();form.set("name",name.trim());form.set("description",description.trim());form.set("image",image);const response=await fetch("/api/characters",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"Character creation failed.");setName("");setDescription("");setImage(null);setMessage(`Created ${data.character.name} with ID ${data.character.characterId}.`);await onChanged();}catch(cause){setMessage(cause instanceof Error?cause.message:"Character creation failed.");}finally{setBusy(false);}}
  async function remove(character:Character){if(!window.confirm(`Remove ${character.name} from this local character library?`))return;const response=await fetch(`/api/characters/${character.id}`,{method:"DELETE"});if(response.ok)await onChanged();else{const data=await response.json().catch(()=>null);setMessage(data?.error||"Character could not be removed.");}}
  return <div className="characters-page"><div className="history-heading"><span className="eyebrow">SORA CHARACTER LIBRARY</span><h2>Character IDs</h2><p>Create and save up to five reusable Sora character IDs. Each generation can use at most two.</p></div><div className="characters-layout"><section className="character-form-card"><h3>Create a character</h3><p>The photo is converted into a short Sora-compatible character clip and uploaded using your configured API key.</p><form onSubmit={create}><label>Character name<input aria-label="Character name" value={name} maxLength={80} required onChange={event=>setName(event.target.value)} placeholder="Mossy"/></label><label>Description<textarea aria-label="Character description" value={description} maxLength={2000} required onChange={event=>setDescription(event.target.value)} rows={5} placeholder="A small moss-covered teapot mascot with brass details…"/></label><label>Reference photo<input aria-label="Character reference photo" type="file" accept="image/jpeg,image/png,image/webp" required onChange={event=>setImage(event.target.files?.[0]??null)}/></label>{image&&<span className="selected-character-file">{image.name}</span>}{message&&<div className={message.startsWith("Created ")?"inline-success":"inline-error"} role="status">{message}</div>}<button className="generate-button" disabled={busy||characters.length>=5}>{busy?<LoaderCircle className="spin" size={17}/>:<BookUser size={17}/>}Create Sora character ID</button></form></section><section className="character-library"><div className="character-library-header"><h3>Saved IDs</h3><span>{characters.length}/5</span></div>{characters.length?characters.map(character=><article key={character.id}><div><strong>{character.name}</strong><code>{character.characterId}</code><p>{character.description}</p></div><button aria-label={`Remove ${character.name}`} onClick={()=>void remove(character)}><Trash2 size={16}/></button></article>):<div className="history-empty"><BookUser size={28}/><strong>No character IDs yet</strong><span>Create one from a non-human character reference photo.</span></div>}</section></div></div>;
}

function Result({job,detailed=false}:{job:Job|null;detailed?:boolean}){return <section className="result-column" aria-live="polite"><div className="result-header"><span className="section-number">03</span><div><h2>Your result</h2><p>Completed clips are also saved in History.</p></div></div><div className={`result-stage ${job?"has-result":"empty"}`}>{!job?<div className="empty-state"><Film size={34}/><strong>Your canvas is clear</strong><span>Create a clip or choose one from History.</span></div>:ready(job)?<video className="generated-video" controls playsInline src={`/api/generations/${job.id}/content`}/>:job.error_message&&!active(job)?<div className="empty-state"><X size={30}/><strong>Generation failed</strong><span>{job.error_message}</span></div>:<div className="rendering-state"><LoaderCircle className="spin" size={30}/><strong>Creating your clip</strong><span>{job.progress?`${job.progress}% complete`:"Waiting for the first update"}</span><div className="progress-track"><span style={{width:`${Math.max(job.progress,4)}%`}}/></div></div>}</div>{job&&<div className="result-actions">{ready(job)&&<a className="download-button" href={`/api/generations/${job.id}/content`} download><Download size={15}/>Download</a>}</div>}{job&&detailed&&<GenerationDetails job={job}/>}</section>}

function GenerationDetails({job}:{job:Job}){const reference=job.request.reference;const videoReference=job.request.videoReference;return <section className="generation-details" aria-labelledby="generation-prompt-heading"><div className="prompt-detail"><span id="generation-prompt-heading">Prompt</span><p>{job.request.prompt}</p></div><dl className="metadata-grid"><div><dt>Model</dt><dd>{labels[job.request.model]}</dd></div><div><dt>Duration</dt><dd>{job.request.seconds} seconds</dd></div><div><dt>Resolution</dt><dd>{fmtSize(job.request.size)}</dd></div><div><dt>Orientation</dt><dd>{outputOrientation(job.request.size)}</dd></div><div><dt>File size</dt><dd>{fileSize(job.asset?.byte_count)}</dd></div><div><dt>Format</dt><dd>{fileFormat(job.asset?.mime_type)}</dd></div><div><dt>Created</dt><dd>{new Date(job.created_at).toLocaleString()}</dd></div><div><dt>Estimated cost</dt><dd>${(job.estimated_cents/100).toFixed(2)}</dd></div><div><dt>Status</dt><dd>{statusLabel(job)}</dd></div><div><dt>Reference image</dt><dd>{reference?`${reference.name} · ${referenceFormat(reference.type)}`:"None"}</dd></div><div><dt>Reference video</dt><dd>{videoReference?`${videoReference.name}${videoReference.selectedStart!==undefined?` · ${videoReference.selectedStart.toFixed(1)}s–${(videoReference.selectedStart+(videoReference.selectedDuration??4)).toFixed(1)}s selected`:""}`:"None"}</dd></div></dl></section>}

function HistoryView({jobs,selected,onSelect,onReuse}:{jobs:Job[];selected:Job|null;onSelect:(id:string)=>void;onReuse:(job:Job)=>void}){return <div className="history-page"><div className="history-heading"><div><span className="eyebrow">YOUR PROJECT</span><h2>Generation history</h2><p>Every request remains available after you close the app.</p></div></div>{!jobs.length?<div className="history-empty"><History size={28}/><strong>No generations yet</strong><span>Your first request will appear here.</span></div>:<div className="history-layout"><div className="history-list">{jobs.map(job=><button key={job.id} className={selected?.id===job.id?"selected":""} onClick={()=>onSelect(job.id)}><span className={`job-status ${ready(job)?"ready":job.error_message?"failed":"working"}`}>{statusLabel(job)}</span><strong>{job.request.prompt}</strong><small>{new Date(job.created_at).toLocaleString()} · {labels[job.request.model]} · {job.request.seconds}s · ${(job.estimated_cents/100).toFixed(2)}</small></button>)}</div>{selected&&<div className="history-detail"><Result job={selected} detailed/><div className="history-actions">{!ready(selected)&&<button className="secondary-button" onClick={()=>onReuse(selected)}>Use settings again</button>}</div></div>}</div>}</div>}
